package com.tuoniao.sijibao.daos;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.tuoniao.sijibao.beans.UserDataBean;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table USER_DATA_BEAN.
 */
public class UserDataBeanDao extends AbstractDao<UserDataBean, Void> {

    public static final String TABLENAME = "USER_DATA_BEAN";

    public UserDataBeanDao(DaoConfig config) {
        super(config);
    }

    public UserDataBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "'USER_DATA_BEAN' (" + //
                           "'FIRST_NAME' TEXT," + // 0: firstName
                           "'LAST_NAME' TEXT);"); // 1: lastName
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'USER_DATA_BEAN'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    public UserDataBean readEntity(Cursor cursor, int offset) {
        UserDataBean entity = new UserDataBean( //
                                                cursor.isNull(offset + 0) ? null :
                                                        cursor.getString(offset + 0), // firstName
                                                cursor.isNull(offset + 1) ? null :
                                                        cursor.getString(offset + 1) // lastName
        );
        return entity;
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }

    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, UserDataBean entity, int offset) {
        entity.setFirstName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setLastName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, UserDataBean entity) {
        stmt.clearBindings();

        String firstName = entity.getFirstName();
        if (firstName != null) {
            stmt.bindString(1, firstName);
        }

        String lastName = entity.getLastName();
        if (lastName != null) {
            stmt.bindString(2, lastName);
        }
    }

    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(UserDataBean entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }

    /** @inheritdoc */
    @Override
    public Void getKey(UserDataBean entity) {
        return null;
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

    /**
     * Properties of entity UserDataBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property FirstName = new Property(0,
                                                              String.class,
                                                              "firstName",
                                                              false,
                                                              "FIRST_NAME");
        public final static Property LastName = new Property(1,
                                                             String.class,
                                                             "lastName",
                                                             false,
                                                             "LAST_NAME");
    }

}
