package com.tuoniao.sijibao.beans;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table APP_DATA_BEAN.
 */
public class AppDataBean {

    private String appVersion;
    private String newVersion;

    public AppDataBean() {
    }

    public AppDataBean(String appVersion, String newVersion) {
        this.appVersion = appVersion;
        this.newVersion = newVersion;
    }

    public String getAppVersion() {
        return appVersion;
    }

    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion;
    }

    public String getNewVersion() {
        return newVersion;
    }

    public void setNewVersion(String newVersion) {
        this.newVersion = newVersion;
    }

}
